name: Run Selenium On GitHub Action
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed    
      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  
        
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Install pandas
        run: pip install pandas

      - name: List Files
        id: list_files
        run: |
          ls > files_list.txt
          cat files_list.txt

      - name: Delete Extra Files
        run: |
          # 刪除所有以 "publicForm" 開頭且以 ".csv" 結尾的檔案
          for file in $(cat files_list.txt); do
            if [[ "$file" == publicForm*.csv ]]; then
              echo "Deleting $file file/"
              rm "$file"
            fi
          done

      - name: Running the Python script
        run: python Selenium-Template.py | more auction.csv

      - name: Move specific CSV files to target folder
        run: |
          # 使用條件將特定格式的 CSV 移動到指定資料夾
          for file in *.csv; do
            if [[ $file == publicForm*.csv ]]; then
              mv "$file" file/
            fi
          done
        
      - name: Commit and Push The Results From Python Selenium Action
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git add file/*.csv
         git commit -m "GitHub Actions Results added"
         git push


         
